server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888 #temporal para que no de errores de arranque

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #por defecto se registra en el servidor pero con esto ya no lo hace
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/