server:
  port: 8888

spring:
  profiles:
    active: native # Se puede tener perfiles para varios desarrollo y produccion
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations